name: "Terraform Safety Check"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Plan and Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # This is the most important part! It shows what WILL happen.
      - name: Terraform Plan
        run: terraform plan -lock=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}